# Generated by Django 4.2.1 on 2023-09-09 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('email_id', models.CharField(max_length=200, null=True)),
                ('mobile_number', models.BigIntegerField(null=True)),
                ('message', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=200, null=True)),
                ('email_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('mobile_number', models.BigIntegerField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='users/')),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('mobile_number', models.BigIntegerField(null=True)),
                ('house_no', models.TextField(null=True)),
                ('area', models.TextField(null=True)),
                ('landmark', models.TextField(null=True)),
                ('pincode', models.CharField(max_length=6, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('default_address', models.BooleanField(default=False)),
                ('email_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
    ]
