# Generated by Django 4.2.1 on 2023-09-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_order_status_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='shop.Order_items', to='shop.product'),
        ),
    ]
